[package]
name = "mobile-test-helper"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
libc = { workspace = true }
libpng-vendored-sys = { path = "../libpng-vendored-sys" }
