name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run tests
      run: cargo test

  test-windows:

    runs-on: windows-2019

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run Cargo tests
      run: cargo test

  test-macos:

    runs-on: macos-12

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run tests
      run: cargo test
    - name: Clean cargo cache 
      run: cargo clean
    - name: Install iOS sim target
      run: rustup target add x86_64-apple-ios
    - name: Prebuild mobile test helper
      run: cargo build --package mobile-test-helper --target x86_64-apple-ios
    - name: Run iOS tests
      working-directory: ./IosTests
      run: xcodebuild test -scheme IosTests -destination "name=iPhone 15"
